import type { Asset, DashboardMetrics, RefreshEvent, Space } from "@/lib/types";

/**
 * Reference demo data used by scripts/seed-demo-data.mjs.
 * Dashboard pages load live data from Supabase in Phase 2+.
 */
export const DEMO_ORGANIZATION = "University of Example";

export const demoSpaces: Space[] = [
  {
    id: "space-001",
    name: "Classroom 204",
    spaceType: "Classroom",
    campus: "Main Campus",
    building: "Science Hall",
    room: "204",
    locationLabel: "Main Campus · Science Hall · Room 204",
    commissionedDate: "2017-06-01",
    commissionedYear: 2017,
    refreshCycleYears: 7,
    recommendedRefreshYear: 2031,
    lifecycleStatus: "upcoming",
    planningStatus: "scheduled",
    plannedRefreshYear: 2031,
    originalCost: 87500,
    forecastAmount: 112400,
    assetCount: 24,
  },
  {
    id: "space-002",
    name: "Executive Conference Room",
    spaceType: "Conference Room",
    campus: "Main Campus",
    building: "Administration Building",
    room: "310",
    locationLabel: "Main Campus · Administration Building · Room 310",
    commissionedDate: "2019-03-01",
    commissionedYear: 2019,
    refreshCycleYears: 7,
    recommendedRefreshYear: 2026,
    lifecycleStatus: "due",
    planningStatus: "scheduled",
    plannedRefreshYear: 2026,
    originalCost: 142000,
    forecastAmount: 178600,
    assetCount: 31,
  },
  {
    id: "space-003",
    name: "Auditorium Technology",
    spaceType: "Auditorium",
    campus: "Main Campus",
    building: "Performing Arts Center",
    locationLabel: "Main Campus · Performing Arts Center",
    commissionedDate: "2014-09-01",
    commissionedYear: 2014,
    refreshCycleYears: 7,
    recommendedRefreshYear: 2025,
    lifecycleStatus: "overdue",
    planningStatus: "deferred",
    plannedRefreshYear: 2028,
    originalCost: 485000,
    forecastAmount: 612000,
    assetCount: 86,
  },
  {
    id: "space-004",
    name: "Building Digital Signage",
    spaceType: "Digital Signage",
    campus: "South Campus",
    building: "Student Union",
    locationLabel: "South Campus · Student Union · Multiple locations",
    commissionedDate: "2020-01-01",
    commissionedYear: 2020,
    refreshCycleYears: 7,
    recommendedRefreshYear: 2034,
    lifecycleStatus: "upcoming",
    planningStatus: "unplanned",
    originalCost: 96000,
    forecastAmount: 124800,
    assetCount: 18,
  },
  {
    id: "space-005",
    name: "Divisible Conference Suite",
    spaceType: "Conference Room",
    campus: "Main Campus",
    building: "Business School",
    locationLabel: "Main Campus · Business School · Rooms 201A–201C",
    commissionedDate: "2018-08-01",
    commissionedYear: 2018,
    refreshCycleYears: 7,
    recommendedRefreshYear: 2032,
    lifecycleStatus: "upcoming",
    planningStatus: "unplanned",
    originalCost: 198500,
    forecastAmount: 256200,
    assetCount: 42,
  },
  {
    id: "space-006",
    name: "Mobile Technology Fleet",
    spaceType: "Mobile Fleet",
    campus: "District-wide",
    building: "—",
    locationLabel: "District-wide deployment",
    commissionedDate: "2022-04-01",
    commissionedYear: 2022,
    refreshCycleYears: 5,
    recommendedRefreshYear: 2027,
    lifecycleStatus: "upcoming",
    planningStatus: "scheduled",
    plannedRefreshYear: 2027,
    originalCost: 320000,
    forecastAmount: 368000,
    assetCount: 120,
  },
  {
    id: "space-007",
    name: "Huddle Room 105",
    spaceType: "Huddle Room",
    campus: "North Campus",
    building: "Engineering Center",
    room: "105",
    locationLabel: "North Campus · Engineering Center · Room 105",
    commissionedDate: "2021-11-01",
    commissionedYear: 2021,
    refreshCycleYears: 7,
    recommendedRefreshYear: 2035,
    lifecycleStatus: "upcoming",
    planningStatus: "unplanned",
    originalCost: 28500,
    forecastAmount: 37200,
    assetCount: 12,
  },
  {
    id: "space-008",
    name: "Training Room B",
    spaceType: "Training Room",
    campus: "Main Campus",
    building: "Library",
    room: "B12",
    locationLabel: "Main Campus · Library · Room B12",
    commissionedDate: "2016-02-01",
    commissionedYear: 2016,
    refreshCycleYears: 7,
    recommendedRefreshYear: 2024,
    lifecycleStatus: "overdue",
    planningStatus: "unplanned",
    originalCost: 54000,
    forecastAmount: 68200,
    assetCount: 19,
  },
];

export const demoAssets: Asset[] = [
  {
    id: "asset-001",
    spaceId: "space-001",
    manufacturer: "Sony",
    modelNumber: "VPL-FHZ75",
    category: "Projector",
    serialNumber: "SN-4482910",
    installDate: "2017-08-15",
    cost: 12500,
    refreshCycleYears: 7,
    recommendedRefreshYear: 2031,
    lifecycleStatus: "upcoming",
    status: "active",
  },
  {
    id: "asset-002",
    spaceId: "space-001",
    manufacturer: "Crestron",
    modelNumber: "DM-NVX-363",
    category: "AV Switcher",
    serialNumber: "CR-8839201",
    ipAddress: "10.24.1.45",
    macAddress: "00:1A:2B:3C:4D:5E",
    installDate: "2017-08-15",
    cost: 3200,
    refreshCycleYears: 7,
    recommendedRefreshYear: 2031,
    lifecycleStatus: "upcoming",
    status: "active",
  },
  {
    id: "asset-003",
    spaceId: "space-001",
    manufacturer: "QSC",
    modelNumber: "CX-Q 8K8",
    category: "Amplifier",
    installDate: "2017-08-15",
    cost: 0,
    refreshCycleYears: 7,
    recommendedRefreshYear: 2031,
    lifecycleStatus: "upcoming",
    status: "active",
  },
  {
    id: "asset-004",
    spaceId: "space-001",
    manufacturer: "Samsung",
    modelNumber: "QM85R",
    category: "Display",
    serialNumber: "SS-9920184",
    installDate: "2028-03-10",
    cost: 4800,
    refreshCycleYears: 7,
    recommendedRefreshYear: 2035,
    lifecycleStatus: "upcoming",
    status: "active",
  },
  {
    id: "asset-005",
    spaceId: "space-001",
    manufacturer: "Shure",
    modelNumber: "MXA910",
    category: "Microphone Array",
    installDate: "2017-08-15",
    cost: 0,
    refreshCycleYears: 7,
    recommendedRefreshYear: 2031,
    lifecycleStatus: "upcoming",
    status: "active",
  },
  {
    id: "asset-006",
    spaceId: "space-002",
    manufacturer: "Cisco",
    modelNumber: "Room Kit Pro",
    category: "Video Conferencing",
    serialNumber: "CS-7729100",
    ipAddress: "10.12.4.88",
    installDate: "2019-06-01",
    cost: 28000,
    refreshCycleYears: 7,
    recommendedRefreshYear: 2026,
    lifecycleStatus: "due",
    status: "active",
  },
  {
    id: "asset-007",
    spaceId: "space-002",
    manufacturer: "LG",
    modelNumber: "86BH5F",
    category: "Display",
    installDate: "2019-06-01",
    cost: 6200,
    refreshCycleYears: 7,
    recommendedRefreshYear: 2026,
    lifecycleStatus: "due",
    status: "active",
  },
];

export const demoRefreshHistory: RefreshEvent[] = [
  {
    id: "event-001",
    spaceId: "space-001",
    type: "initial_deployment",
    date: "2017-08-15",
    description: "Initial classroom technology deployment",
    cost: 87500,
  },
  {
    id: "event-002",
    spaceId: "space-001",
    type: "partial_refresh",
    date: "2028-03-10",
    description: "Display replaced — Samsung QM85R installed",
    cost: 4800,
  },
  {
    id: "event-003",
    spaceId: "space-002",
    type: "initial_deployment",
    date: "2019-06-01",
    description: "Executive conference room initial deployment",
    cost: 142000,
  },
  {
    id: "event-004",
    spaceId: "space-003",
    type: "full_refresh",
    date: "2022-01-20",
    description: "Full auditorium refresh — lighting and control systems",
    cost: 185000,
  },
];

export const demoDashboardMetrics: DashboardMetrics = {
  totalPortfolioValue: 2_415_500,
  fiveYearForecast: 1_842_000,
  dueThisYear: 320_600,
  overdue: 680_200,
  deferred: 612_000,
  forecastByYear: [
    { year: 2026, amount: 320_600 },
    { year: 2027, amount: 412_000 },
    { year: 2028, amount: 298_400 },
    { year: 2029, amount: 356_800 },
    { year: 2030, amount: 454_200 },
  ],
};

export function getSpaceById(id: string): Space | undefined {
  return demoSpaces.find((space) => space.id === id);
}

export function getAssetsBySpaceId(spaceId: string): Asset[] {
  return demoAssets.filter((asset) => asset.spaceId === spaceId);
}

export function getRefreshHistoryBySpaceId(spaceId: string): RefreshEvent[] {
  return demoRefreshHistory.filter((event) => event.spaceId === spaceId);
}
